import type { Metadata } from "next";
import { MainContainer } from "../../context/MainContainer";
import { SessionAuthProvide } from "../../context/SessionProvide";

import "../../node_modules/@syncfusion/ej2/fluent.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "LSQA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionAuthProvide>
          <MainContainer>{children}</MainContainer>
        </SessionAuthProvide>
      </body>
    </html>
  );
}
